<head>
    <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <script src="https://www.google.com/recaptcha/api.js?render=6LdZX5YjAAAAAL6MUfw8X2Zq2rerHeb7GrcvbgdP"></script> 

</head>

<meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
  @keyframes ldio-v9tbisjpha {
  0% { transform: rotate(0) }
  100% { transform: rotate(360deg) }
}
.ldio-v9tbisjpha div { box-sizing: border-box!important }
.ldio-v9tbisjpha > div {
  position: absolute;
  width: 144px;
  height: 144px;
  top: 28px;
  left: 28px;
  border-radius: 50%;
  border: 16px solid #000;
  border-color: #0a0a0a transparent #0a0a0a transparent;
  animation: ldio-v9tbisjpha 1s linear infinite;
}
.ldio-v9tbisjpha > div:nth-child(2) { border-color: transparent }
.ldio-v9tbisjpha > div:nth-child(2) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-v9tbisjpha > div:nth-child(2) div:before, .ldio-v9tbisjpha > div:nth-child(2) div:after { 
  content: "";
  display: block;
  position: absolute;
  width: 16px;
  height: 16px;
  top: -16px;
  left: 48px;
  background: #0a0a0a;
  border-radius: 50%;
  box-shadow: 0 128px 0 0 #0a0a0a;
}
.ldio-v9tbisjpha > div:nth-child(2) div:after { 
  left: -16px;
  top: 48px;
  box-shadow: 128px 0 0 0 #0a0a0a;
}
.loadingio-spinner-dual-ring-odnrhz1zao {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-v9tbisjpha {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-v9tbisjpha div { box-sizing: content-box; }
/* generated by https://loading.io/ */

  
  
.login-root {
    background: #fff;
    display: block;
    width: 100%;
    overflow: hidden;
    height: 100%;
}
.loginbackground {
    min-height: 692px;
    position: fixed;
    bottom: 0;
    left: 0;
    right: 0;
    top: 0;
    z-index: 0;
    overflow: hidden;
}
.flex-flex {
    display: flex;
}
.align-center {
  align-items: center; 
}
.center-center {
  align-items: center;
  justify-content: center;
}
.flex-direction--column {
    -ms-flex-direction: column;
    flex-direction: column;
}
.box-divider--light-all-2 {
    box-shadow: inset 0 0 0 2px #e3e8ee;
}
.box-background--blue {
    background-color: #5469d4;
}
.box-background--white {
  background-color: #ffffff; 
}
.box-background--blue800 {
    background-color: #212d63;
}
.box-background--gray100 {
    background-color: #e3e8ee;
}
.box-background--cyan200 {
    background-color: #7fd3ed;
}
.padding-top--64 {
  padding-top: 64px;
}
.padding-top--24 {
  padding-top: 24px;
}
.padding-top--48 {
  padding-top: 48px;
}
.padding-bottom--24 {
  padding-bottom: 20px;
}
.padding-horizontal--48 {
  padding: 48px;
}
.padding-horizontal--24 {
    padding: 25px 40px;
}
.padding-bottom--15 {
  padding-bottom: 15px;
}


.formbg {
    margin: 0px auto;
    width: 100%;
    max-width: 448px;
    background: white;
    border-radius: 4px;
    box-shadow: rgba(60, 66, 87, 0.12) 0px 7px 14px 0px, rgba(0, 0, 0, 0.12) 0px 3px 6px 0px;
}

.grid--50-50 {
    display: grid;
    grid-template-columns: 50% 50%;
    align-items: center;
}

.field input{
    font-size: 16px;
    line-height: 18px;
    width: 100%;
    border: unset;
    padding:10px;
    color: #000;
    padding: 5px 20px;
    height: 45px;
    border-radius: 5px;
    outline-color: rgb(84 105 212 / 0.5);
    background-color: rgb(255, 255, 255);
    box-shadow: rgba(0, 0, 0, 0) 0px 0px 0px 0px, 
                rgba(0, 0, 0, 0) 0px 0px 0px 0px, 
                rgba(0, 0, 0, 0) 0px 0px 0px 0px, 
                rgba(60, 66, 87, 0.16) 0px 0px 0px 1px, 
                rgba(0, 0, 0, 0) 0px 0px 0px 0px, 
                rgba(0, 0, 0, 0) 0px 0px 0px 0px, 
                rgba(0, 0, 0, 0) 0px 0px 0px 0px;
}

.fieldtime input {
    font-size: 15px;
    width: 100%;
    padding:10px;
    border: unset;
    border-radius: 4px;
    outline-color: rgb(84 105 212 / 0.5);
    background-color: rgb(255, 255, 255);
    box-shadow: rgba(0, 0, 0, 0) 0px 0px 0px 0px, 
                rgba(0, 0, 0, 0) 0px 0px 0px 0px, 
                rgba(0, 0, 0, 0) 0px 0px 0px 0px, 
                rgba(60, 66, 87, 0.16) 0px 0px 0px 1px, 
                rgba(0, 0, 0, 0) 0px 0px 0px 0px, 
                rgba(0, 0, 0, 0) 0px 0px 0px 0px, 
                rgba(0, 0, 0, 0) 0px 0px 0px 0px;
}

input[type="submit"] {
    background-color: #236e8d;
    box-shadow: rgba(0, 0, 0, 0) 0px 0px 0px 0px, 
                rgba(0, 0, 0, 0) 0px 0px 0px 0px, 
                rgba(0, 0, 0, 0.12) 0px 1px 1px 0px, 
                rgb(84, 105, 212) 0px 0px 0px 1px, 
                rgba(0, 0, 0, 0) 0px 0px 0px 0px, 
                rgba(0, 0, 0, 0) 0px 0px 0px 0px, 
                rgba(60, 66, 87, 0.08) 0px 2px 5px 0px;
    color: #fff;
    font-weight: 600;
    cursor: pointer;
}
.field-checkbox input {
    width: 20px;
    height: 15px;
    margin-right: 5px; 
    box-shadow: unset;
    min-height: unset;
}
.field-checkbox label {
    display: flex;
    align-items: center;
    margin: 0;
}


.animationRightLeft {
  animation: animationRightLeft 2s ease-in-out infinite;
}
.animationLeftRight {
  animation: animationLeftRight 2s ease-in-out infinite;
}
.tans3s {
  animation: animationLeftRight 3s ease-in-out infinite;
}
.tans4s {
  animation: animationLeftRight 4s ease-in-out infinite;
}

@keyframes animationLeftRight {
  0% {
    transform: translateX(0px);
  }
  50% {
    transform: translateX(1000px);
  }
  100% {
    transform: translateX(0px);
  }
} 

@keyframes animationRightLeft {
  0% {
    transform: translateX(0px);
  }
  50% {
    transform: translateX(-1000px);
  }
  100% {
    transform: translateX(0px);
  }
} 
.button {
  border-radius: 4px;
  background-color: #236e8d;
  border: none;
  color: #FFFFFF;
  text-align: center;
  font-size: 15px;
  padding: 10px;
  width: 100%;
  transition: all 0.5s;
  cursor: pointer;
  margin: 0px;
}

.button span {
  cursor: pointer;
  display: inline-block;
  position: relative;
  transition: 0.5s;
}

.button span:after {
  content: '\00bb';
  position: absolute;
  opacity: 0;
  top: 0;
  right: -20px;
  transition: 0.5s;
}

.button:hover span {
  padding-right: 25px;
}

.button:hover span:after {
  opacity: 1;
  right: 0;
}
select {
    line-height: 18px;
    width:100%;
   -webkit-appearance:none;
   -moz-appearance:none;
   -ms-appearance:none;
   appearance:none;
   outline:0;
   box-shadow:none;
   border:1px solid #ecedef;
   background-image: none;
   flex: 1;
   padding:10px;
    border-radius: 50px;
   color:#000;
   cursor:pointer;
    height: 45px;
    border-radius: 5px;
   outline-color: rgb(84 105 212 / 0.5);
    background-color: rgb(255, 255, 255);
    box-shadow: rgba(0, 0, 0, 0) 0px 0px 0px 0px, 
                rgba(0, 0, 0, 0) 0px 0px 0px 0px, 
                rgba(0, 0, 0, 0) 0px 0px 0px 0px, 
                rgba(60, 66, 87, 0.16) 0px 0px 0px 1px, 
                rgba(0, 0, 0, 0) 0px 0px 0px 0px, 
                rgba(0, 0, 0, 0) 0px 0px 0px 0px, 
                rgba(0, 0, 0, 0) 0px 0px 0px 0px;
   font-family: 'Open Sans', sans-serif;
}
select::-ms-expand {
   display: none;
}
.select {
   position: relative;
   display: flex;
   width: 100%;
   height: 2.5em;
   line-height: 3;
   overflow: hidden;
   border-radius: .25em;
}
.select::after {
   /*content: '\25BC';*/
   position: absolute;
   top: 0;
   right: 0;
   padding: 0 1em;
   background: #2b2e2e;
   cursor:pointer;
   pointer-events:none;
   transition:.25s all ease;
}
.select:hover::after {
   color: #23b499;
}
</style>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">

  <div class="login-root" style="background-color:transparent; vertical-align: middle !important;">
    <div class="box-root flex-flex flex-direction--column" style="flex-grow: 1;">
      
      <div class="box-root flex-flex flex-direction--column" style="flex-grow: 1;">
        <div class="formbg-outer">
          <div class="">
            <div class="formbg-inner padding-horizontal--24">
              
              <h2 style="font-size:25px !important;font-weight:bold;font-family: 'Roboto', sans-serif;text-align:center;margin-top:14px;    margin-bottom: 0px;color:#fff">Book an Appointment</h2> <br>
              <form id="comment_form" action="https://www.gbrclinic.com/admin/front-end/save.php" method="post" enctype="multipart/form-data">
                  <div class="row">
                      <div class="col-md-6 col-xs-12 col-sm-12">
                        <div class="field padding-bottom--24">
                            <!--<label for="phone" style="font-size:17px!important;color:#000;margin-left: 15px;">Name</label>-->
                          <input placeholder="Name" type="text" id="name"  name="name"  required autocomplete="off">
                          <input type="hidden" id="pagename" value="<?php echo $_SERVER['REQUEST_URI']; ?>">
                        </div>
                      </div>
                      <div class="col-md-6 col-xs-12 col-sm-12">
                          <div class="field padding-bottom--24">
                              <!--<label for="phone" style="font-size:17px!important;color:#000;margin-left: 15px;">Email</label>-->
                          <input placeholder="Email" type="email" id="email"  name="email"  required autocomplete="off">
                        </div>
                      </div>  
                      
                      <div class="col-md-6 col-xs-12 col-sm-12">
                           <div class="field padding-bottom--24">
                               <!--<label for="phone" style="font-size:17px!important;color:#000;margin-left: 15px;">Phone</label>-->
                              <input placeholder="Mobile" id="phone" type="number"  name="phone" required autocomplete="off">
                            </div>
                      </div> 
                      <div class="col-md-6 col-xs-12 col-sm-12">
                           <div class="field padding-bottom--24">
                              <!--<label for="phone" style="font-size:17px!important;color:#fff;margin-left: 15px;">Services</label>-->
                             
                                  <select id="doctor"  name="doctor" required autocomplete="off">
                                 <option>Select Services</option>
                               </select>
                            
                              
                            </div>
                      </div> 
                      <div class="col-md-6 col-xs-12 col-sm-12">
                           <div class="field padding-bottom--24">
                              <label for="phone" style="font-size:17px!important;color:#fff;margin-left: 15px;">Appointment Date</label>
                              <input type="date"  id="appdate" placeholder="Phone" name="appdate" min="<? echo date('Y-m-d'); ?>"  required autocomplete="off" style="min-width:100%!important;font-size: 16px;
    line-height: 18px;
    width: 100%;
    border: unset;
    padding:10px;">
                            </div>
                      </div> 
                      <div class="col-md-6 col-xs-12 col-sm-12">
                           <div class="field padding-bottom--24">
                      <label for="phone" style="font-size:17px!important;color:#fff;margin-left: 15px;">Appointment Time</label>
                      
                          <select style="color:#000; padding: 5px;" id="apptime" name="apptime" required autocomplete="off">
                         
                       </select>
                       
                 
                    
                      
                    </div>
                      </div> 
                  </div>
                
                
               
               
                    
                
                <br>
                <div class="field padding-bottom--24">
                    
                            <center>
                                <input type="submit" name="submit" value="Book Now" style="width:210px;background-color:#888;font-size:20px">
                            </center>
                            <div id="result"></div>
                            
                                  

                    
                    
                    
                    <!--<center>-->
                    <!--    <input type="submit" name="submit" value="Book Now" style="width:210px;background-color:#623192;font-size:20px">-->
                    <!--</center>-->
                  
                </div>
              </form>
              <div id="loading" style="padding:20px;display:none;background-color:#fff;border-radius: 15px;">
                                       <div class="loadingio-spinner-dual-ring-odnrhz1zao"><div class="ldio-v9tbisjpha">
                                          <div></div><div><div></div></div>
                                          </div></div></div>
            </div>
          </div>
         
        </div>
      </div>
    </div>
  </div>
  
  
  <script>
       // when form is submit
    $('#comment_form').submit(function() {
        // we stoped it
        event.preventDefault();
	$("#comment_form").hide();
	$("#loading").show();
        var name = $('#name').val();
        var email = $("#email").val();
        var phone = $("#phone").val();
        var doctor = $("#doctor").val();
        var appdate = $("#appdate").val();
        var apptime = $("#apptime").val();
        var pagename = $("#pagename").val();
        // needs for recaptacha ready
        grecaptcha.ready(function() {
            // do request for recaptcha token
            // response is promise with passed token
            grecaptcha.execute('6LdZX5YjAAAAAL6MUfw8X2Zq2rerHeb7GrcvbgdP', {action: 'create_comment'}).then(function(token) {
                // add token to form
                $('#comment_form').prepend('<input type="hidden" name="g-recaptcha-response" value="' + token + '">');
                    $.post("../admin/front-end/save.php",{name: name,email: email,phone: phone,doctor: doctor,appdate: appdate,apptime:apptime,pagename: pagename, token: token}, function(result) {
                            console.log(result);
                            if(result.success) {

                                    alert('Thanks! We will contact you shortly.')
                                    $("#comment_form").show();
                                    $(".form-control").val('');
	                                $("#loading").hide();
	                                window.location = 'https://www.gbrclinic.com/thank-you.php';
                            } else {
                                    alert('Mail not Sent!')
                                    $("#comment_form").show();
	                                $("#loading").hide();
                            }
                    });
            });;
        });
  });
  </script>

  
  
  
  <script>
  (function($){
   $( document ).ready(function() {
        var pagename = $('#pagename').val();
    // alert()
	$.ajax({
		 url: 'https://www.gbrclinic.com/admin/front-end/ajax/form.php',
		 type: 'POST',
		 data: {
		     pagename:pagename,
	         loadDepartmentDetails:'loadDepartmentDetails'
	   },
		 beforeSend : function() {
		  $('body').css('cursor', 'progress');
		 },
		 success : function(data) {
		  $('#doctor').html(data);

		  $('body').css('cursor', 'default');

		 },
		 async : false
	 });
});
 	 
  })(jQuery);
  



 (function($){ $(document).on('change','#appdate',function() {
    var doctorID = $('#doctor').val();
    if(doctorID == ''){
        alert("Select Doctor");
        $('#appdate').val('');
        return false;
    }else{
        var doctorID = $('#doctor').val();
    var appdate = $('#appdate').val();
    // alert(appdate)
  $.ajax({
     url: 'https://www.gbrclinic.com/admin/front-end/ajax/app.php',
     type: 'POST',
     data: {
      
       doctorID:doctorID,
       appdate:appdate,
       checkDocAppointment:'checkDocAppointment'
     },
     beforeSend : function() {
      $('body').css('cursor', 'progress');
      //alert(coldCallID);
     },
     success : function(data) {
        //  alert(data);
        if(data == ''){
            alert("Doctor is unavailable! Kindly Choose another date");
            $('#appdate').val('');
            $('#apptime').html('');
        }else{
            $('#apptime').html(data);
        }
      
      
      $('body').css('cursor', 'default');
     },
     async : false
   });
    }
     
});  })(jQuery);

 (function($){ $(document).on('change','#doctor',function() {
    var doctorID = $('#doctor').val();
    $('#appdate').val('');
    $('#apptime').html('');
     
}); })(jQuery);

</script>
<!--<script src="js/appointment.js"></script>-->
